name: DevSecOps-Advanced-Pipeline

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # 1. SCA SCAN (Snyk)
      - name: Run Snyk SCA Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true 

      # 2. SAST SCAN (SonarCloud)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sairam-Appsec_DevSecOps-Cloud-Project
            -Dsonar.organization=sairam-appsec

# STEP 3: Jira Login (Add this new step!)
      - name: Login to Jira
        if: failure()
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      # STEP 4: Create Jira Ticket on Failure
      - name: Create Jira Issue on Failure
        if: failure()
        uses: atlassian/gajira-create@v3
        with:
          project: 'KAN' # Nuvvu pampina image lo unna project key
          issuetype: 'Bug'
          summary: 'Security Vulnerabilities Detected'
          description: 'High severity issues found. Check Snyk/SonarCloud dashboards.'